### ISSUE TITLE
Onde estão os links para os vídeos das aulas 3, 4, 5, 6 e 8??

### ISSUE THREAD

**Issue by marcostc** [alexlopespereira/curso_ciencia_dados2020#102]
Só achei os vídeos das aulas 1,2 e 7.

Poderiam me informar os demais????

**Comment by claytonsilva007** [comment]
As aulas estão postadas no Google Classroom.

**Comment by marcostc** [comment]
Não estou achando as aulas mencionadas no JupterNotebook

**Comment by marcostc** [comment]
Não estou achando as aulas 3 a 6 e 8 no Classroom.  Poderia me passar o link ou entrar em contato comigo na sala 5?
