### ISSUE TITLE
Iniciar repositório no GitHub

### ISSUE THREAD

**Issue by Fabibarreiros** [alexlopespereira/curso_ciencia_dados2020#106]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.
Já criei o repositório no GitHub, mas não consegui fazer o push.
**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
```

**Log de erro**
```
The authenticity of host 'github.com (140.82.114.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.114.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by rodrigobotelho** [comment]
Se vc usar o protocolo git, ele vai usar ssh, ai vc precisa cadastrar sua chave RSA. Tente usar o link https. Ao copiar do github, tem duas opções, uma delas é o https

**Comment by Fabibarreiros** [comment]
Perdão, nao entendi. Imaginei que vc iria atender em outra sala


Em qui., 22 de out. de 2020 às 16:27, Rodrigo Dias Botelho Pellicano <
notifications@github.com> escreveu:
