### ISSUE TITLE
Divergência no resultado do exercício 3.7

### ISSUE THREAD

**Issue by mlnunex** [alexlopespereira/curso_ciencia_dados2020#11]
**Objetivo que desejo atingir**
Quando comparo os nomes de municípios dos do dataframe PIB e do dataframe População, identifiquei 16 nomes de municípios com grafia diferente, são eles :
1166      Olho d'Água do Borges
1621         São Vicente Férrer
1775             Gracho Cardoso
1851                     Araçás
2031                       Iuiu
2095    Muquém do São Francisco
2174            Santa Terezinha
2801                Passa Vinte
2834               Pingo d'Água
3106            Atílio Vivacqua
3341             Biritiba Mirim
3451                   Florínea
3520                     Itaoca
3826     São Luiz do Paraitinga
4455               Lauro Müller
4551       São Cristóvão do Sul

**A solução que já criei até o momento**
```
def merge_pop_pib(path_pop, path_pib):
    """retorne um dataframe resultante do merge dos dados do pib e da população
    """
    f = lambda x : x[2][:len(x[2])-5]
    df_pib = pd.read_excel(path_pib, dtype= {'Unnamed: 1' : str}, skiprows=3, skipfooter=1)
    df_pib.rename(columns={'Unnamed: 0': 'nivel', 'Unnamed: 1': 'cod_ibge7', 'Unnamed: 2': 'municipio UF'}, inplace=True)
    df_pop = pd.read_excel(path_pop, dtype={'cod_munic': str, 'cod_uf': str})
    df_pop['municipio UF'] = df_pop['municipio']+' ('+df_pop['uf']+')'
    df_pib['municipio_y'] = df_pib.apply(f, axis='columns')
    df = df_pib.join(df_pop.set_index('municipio UF'), on = 'municipio UF')
    return df

def compare_df_cols(df, col1, col2):
    """retorne a quantidade de registros em que o valor do registro na coluna col1 difere do valor em col2
    """
    df[df[col1]!= df[col2]].shape[0]
    return (df[col1] != df[col2]).value_counts().to_dict()[True]

path_pib = '../../curso_ciencia_dados2020/data/originais/pib/pib_municipios.xlsx'
path_pop='../../curso_ciencia_dados2020/data/originais/populacao/estimativa_dou_2017.xlsx'
df_pib_pop = merge_pop_pib(path_pop, path_pib)
compare_df_cols(df_pib_pop, 'municipio', 'municipio_y')


**Log de erro**

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-162-898a355610c1> in <module>
      1 # Validação para nota
----> 2 assert compare_df_cols(df_pib_pop, 'municipio', 'municipio_y') == 0

AssertionError: 

Porque deveria retornar 0 diferenças segundo a correção. Avaliando as planilhas o resultado que encontrei me pareceu consistente.
```

**Comment by rodrigobotelho** [comment]
Você está correto. Basta atualizar as aulas que o resultado vai ser 16 mesmo. Só uma dica, ao invés de usar o value_counts(), vc pode usar o sum()
