### ISSUE TITLE
Dúvida sobre como fazer a importação de uma função de um módulo de forma encadeada de diretorios

### ISSUE THREAD

**Issue by otaviosbarbosa** [alexlopespereira/curso_ciencia_dados2020#113]
**SALA 9**

**Objetivo que desejo atingir**
fazer a importação de uma função de um módulo de forma encadeada de diretorios

**A solução que já criei até o momento**
from modulos.operacoes.matematica import soma

Cole aqui o código que você já criou para atingir seu objetivo.
from modulos.operacoes.matematica import soma

**Log de erro**
```
Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-29-addd664f7c19>", line 1, in <module>
    from modulos.operacoes.matematica import soma

  File "/home/jovyan/work/cdenap_2020-2/Aula1_Ex01/modulos/operacoes/matematica.py", line 11
    if b ! = 0:
         ^
SyntaxError: invalid syntax
```

**Comment by stefanomozart** [comment]
Otávio, se você adicionou o diretório "modulo", no search path do python, então você pode importar os módulos que estão dentro desse diretório. Assim, a seguinte linha de código deveria funcionar:

```
from operacoes.matematica import soma
```

**Comment by stefanomozart** [comment]
Agora eu notei o erro na mensagem de erro. Você tem um erro de sintaxe no arquivo matematica.py, na linha 11. Você precisa retirar o espaço entre a exclamação e o igual. Troque 

```
if b ! = 0:
```
por
```
if b != 0:
```
