### ISSUE TITLE
duvidas para entrega dos exercicios

### ISSUE THREAD

**Issue by ricardacarolina** [alexlopespereira/curso_ciencia_dados2020#115]
nome: Ricarda Carolina
Sala : 4

Devemos entregar o exercicios preenchendo a primera tela, a segunda (faça seus testes aqui) pode ficar em branco, e testamos a validação para nota, certo? Além disso temos que submeter o warmup também, ok?
E por último não entendi a linha de comando 
raise NotImplementedError() para que serve? Fiz meu código com essa linha em comentário, está correto?

**Comment by stefanomozart** [comment]
Você só precisa criar a sua solução na primeira célula de cada caderno. As outras células são para te ajudar, testando sua solução e validando com alguns casos de teste e as respostas esperadas.

A instrução 'NotImplementedError()' é para ajudar o professor com a validação automática. Você pode removê-la. Ela está lá apenas para gerar um alerta caso o aluno entregue o caderno sem escrever nenhuma solução.
