### ISSUE TITLE
aula1_ex4 - erro no assert - "create_dict" is not defined

### ISSUE THREAD

**Issue by ricardacarolina** [alexlopespereira/curso_ciencia_dados2020#121]
nome - Ricarda Carolina
sala - 4

O código abaixo rodou no ambiente de testes, porem na validação usando o assert, deu a falha de "name create_dict" is not defined, mas ele está criado, não entendi

def create_dict(n):
    dicionario = {}
    aux=1
    while aux < n:
        dicionario[aux] = {aux**2}
        aux=aux+1
    return dicionario

**Comment by stefanomozart** [comment]
```
def create_dict(n):
    dicionario = {}
    aux=1
    while aux < n:
        dicionario[aux] = {aux**2}
        aux=aux+1
    return dicionario
```

Não sei como está a formatação no seu caderno, mas com a formatação correta, seu código ainda teria um probleminha: em lugar de criar um novo dicionário na linha `dicionario[aux] = {aux**2}`, você quer apenas atribuir o valor, dessa forma: `dicionario[aux] = aux**2` (sem as chaves).
