### ISSUE TITLE
Problema no Validate da questao 1.2

### ISSUE THREAD

**Issue by seraleroc** [alexlopespereira/curso_ciencia_dados2020#125]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.
Resolver o problema do validate da questao 1.2
**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
```
def maior(* lista):
    cont = maior = 0
    print ('\nAnalisando os valores da lista...')
    for valor in lista:
        print(f'{valor} ', end='')
        if cont ==0:
            maior = valor
        else:
            if valor > maior:
                maior = valor
        cont += 1
    print(f'O maior valor da lista informada foi {maior}.')
**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-6855c176bd24> in <module>
      1 # Validação para nota
----> 2 assert maior([1,0,-1,100,7]) == 100
      3 assert maior([-100,-1580,-1,-9100,-77]) == -1

AssertionError:

**Comment by stefanomozart** [comment]
A sua função precisa retornar um valor. Use a expressão `return`:

```
def maior(lista):
    cont = maior = 0
    print ('\nAnalisando os valores da lista...')
    for valor in lista:
        print(f'{valor} ', end='')
        if cont ==0:
            maior = valor
        else:
            if valor > maior:
                maior = valor
        cont += 1
    print(f'O maior valor da lista informada foi {maior}.')
    return maior
```
