### ISSUE TITLE
exercicio aula 6 exercicio 5 e problema de download do trabalho final

### ISSUE THREAD

**Issue by ricardacarolina** [alexlopespereira/curso_ciencia_dados2020#126]
Aluna Ricarda Carolina Rende
Sala 4
1) ex 6.5 fiquei com dúvida no enunciado porque os gráficos pairplot não fizeram sentido para mim já que os dados do morb são de 2020 e o gini é 2010. O código que fiz está abaixo:

path_morbidade = 'https://github.com/alexlopespereira/curso_ciencia_dados2020/raw/master/data/originais/morbidade/consolidado/morbidade.csv'

df_morb = pd.read_csv(path_morbidade, sep=';', na_values='-',decimal=',',dtype={'cod_ibge6': str,'Dias_permanência': float, 'Internações': float, 'Valor_total':float })
df_morb.rename(columns={'Município':'municipio'}, inplace=True)
#df_morb.head()
grouped=df_morb.groupby(['municipio'])
df_morb2 = grouped.agg({'Internações':'sum','Óbitos':'sum'})
#df_morb2.head()
path_gini='../../curso_ciencia_dados2020/data/originais/gini/ginibr.csv'
df_gini = pd.read_csv(path_gini, sep=';',na_values='...', decimal = ',', skiprows = 2)
df_gini.rename(columns={'Município':'municipio'}, inplace=True)
df_gini['municipio'] = df_gini['municipio'].str.slice(start=7)
df_gini = df_gini[['municipio','2010']]
#df_gini.head()
df_morb2gini=pd.merge(df_morb2,df_gini, on='municipio')
#df_morb2gini.head()
sns.set() # Ajusta valor padrão de tema, escala e paleta de cor
sns.pairplot(data=df_morb2gini)

2) Trabalho final - estou usando uma planilha excel que coloquei no google drive, busquei o link para compartilhamento e retirei a restrição (arquivo se chama acessosbl2.xlsx, entretanto dá falha no momento que faço a leitura como abaixo:

path = 'https://drive.google.com/file/d/1rDQ14Wlc8lQMZKQfeQOeXTl8bQz4wggl/view?usp=sharing'
df = pd.read_excel(path_pop, sheet_name='acessobl')
df.head()

**Comment by stefanomozart** [comment]
**Sobre a questão 6.5:**
Não é necessário realizar a agregação por município, só o merge dos dois datasets e depois o pairplot das seguintes colunas: 'Internações', 'Óbitos', '2010'.

Realmente, não faz muito sentido estudar variáveis de períodos tão díspares. A intenção do exercício essa só ajudar os alunos a usarem um pairplot. Com as três colunas selecionadas, dá pra inferir que `Internações` tem correlação positiva com `Óbitos` , mas não com `2010`.

**Sobre o trabalho final:**
Já tentou baixar essa planilha e rodar o carregamento do dataframe localmente?
