### ISSUE TITLE
Exercício 8.1 - erro de list index out of range

### ISSUE THREAD

**Issue by fcdealmeida** [alexlopespereira/curso_ciencia_dados2020#136]
**Objetivo que desejo atingir**
Para a primeira página do resultado dessa pesquisa no Google, obter **todos** os dados dos apps solicitados no exercício 8.1, que são os ".gov.br" inurl:play.google.com.

**A solução que já criei até o momento**
Obtive sucesso para a formação do dicionário do primeiro app, mas o programa dá erro de 'list index out of range' na formação do 2º app da página pesquisada e trava.

**Cole aqui o código que você já criou para atingir seu objetivo**
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(ChromeDriverManager().install())
url = "https://www.google.com"
driver.get(url)
input = driver.find_element_by_xpath('//input[@name="q"]')
input.send_keys('".gov.br" inurl:play.google.com')
input.send_keys(Keys.RETURN)
divs_g = driver.find_elements_by_xpath('//div[@class="g"]')
dataset = []
for d in divs_g:
    nome_app = "-".join(d.find_element_by_xpath(".//h3/span").text.split("–")[0:-1]).strip()
    url_app = d.find_element_by_xpath(".//a").get_attribute("href")
    spans = d.find_elements_by_xpath(".//div/div/div/div/span")
    nota_app = float(spans[1].text.split(":")[-1].replace(",", "."))
    votos_app = int(spans[2].text.split(" ")[0].replace(".", ""))
    resultado = {"nome_app": nome_app, "url_app": url_app, "nota_app": nota_app, "votos_app": votos_app}
    dataset.append(resultado)

**Log de erro**
IndexError: list index out of range

![image](https://user-images.githubusercontent.com/72361970/100397988-6b7ccc80-302b-11eb-92da-42f761ace867.png)

**Comment by stefanomozart** [comment]
O problema era a mudança na lista de resultados, que passou a exibir a página do governo. A solução é adicionar um teste após a linha 39, pra testar se a variável `span` realmente contem uma lista.
