### ISSUE TITLE
Problemas no exercício 5.5

### ISSUE THREAD

**Issue by arthuribge** [alexlopespereira/curso_ciencia_dados2020#16]
**Objetivo que desejo atingir**
Plotar o gráfico conforme pedido no enunciado.

**A solução que já criei até o momento**
def load_gini(path_gini):
    df = pd.read_csv(path_gini, sep=';', engine='python', skiprows=2, skipfooter=2, decimal=',', na_values = '...')
    df['cod'] = df['Município'].str[:6]
    df['Município'] = df['Município'].str[7:]
    return df

def merge_morb_gini(path_gini, path_morbidade):
    dfm = pd.read_csv(path_morbidade, sep=';', decimal=',', na_values = '-', low_memory=False, dtype={'cod_ibge6': str})
    dfm = dfm[['cod_ibge6', 'Município', 'Óbitos', 'Internações']]
    g = dfm.groupby(['cod_ibge6', 'Município'])
    dfm_agg = g.sum()
    
    dfg = load_gini(path_gini)
    dfg.rename(columns={'cod': 'cod_ibge6'}, inplace=True)
    del dfg['1991']
    del dfg['2000']
    
    df = pd.merge(dfg, dfm_agg, on='cod_ibge6')
    return df

path_morbidade = '../../curso_ciencia_dados2020/data/originais/morbidade/consolidado/morbidade.csv'
path_gini = '../../curso_ciencia_dados2020/data/originais/gini/ginibr.csv'
df = merge_morb_gini(path_gini, path_morbidade)
sns.pairplot(data=df, vars=['Internações', 'Óbitos', '2010'])

**Log de erro**
No gráfico de resultado as células 1x1 e 2x2 apresentam apenas uma barra vertical, porém na 3x3 aparecem várias barras, está certo isso?

**Comment by rodrigobotelho** [comment]
Não entendi algumas partes do seu código. Pq vc fez o groupby no df de morbidade? A princípio não tem problema aparecer várias barras. Se puder plotar o resultado facilita pra gente!
