### ISSUE TITLE
Funcao do exercicio 1.4

### ISSUE THREAD

**Issue by tiagolandi** [alexlopespereira/curso_ciencia_dados2020#19]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.

**A solução que já criei até o momento**
```
def create_dict(n):
    dic = {}
    for val in range(1, n + 1):
        return dic[val] = val**2

**Log de erro**
 return dic[val] = val**2
                    ^
SyntaxError: invalid syntax

**Comment by rodrigobotelho** [comment]
O erro é q vc tá fazendo um return e ao mesmo tempo uma atribuição. Observe que esse return não faz muito sentido nesse lugar q você colocou.

**Comment by alexlopespereira** [comment]
resolvido?

**Comment by tiagolandi** [comment]
nao, nao consegui validar aqui

**Comment by rodrigobotelho** [comment]
resolvido
