### ISSUE TITLE
Dúvida conceitual para retirar um valor

### ISSUE THREAD

**Issue by taniseb** [alexlopespereira/curso_ciencia_dados2020#22]
A principal dúvida é para entender como chegar em um par em que há mais de um key,value por elemento do dicionário, tendo em vista que nos exercícios anteriores a execução era um pouco mais simples.
Mesa 5

**Comment by rodrigobotelho** [comment]
Taniseb, pra criar uma issue, é bom seguir o template. É bom falar qual o exercício, postar o código feito.
