### ISSUE TITLE
Exercício 10 - NameError: name 'np' is not defined

### ISSUE THREAD

**Issue by lmgbsb** [alexlopespereira/curso_ciencia_dados2020#27]
**Objetivo que desejo atingir**
 converter para celcius um array de temperaturas em Fahrenheit. Arredonde o resultado até 2a casa decimal usando a função .round(decimals=2) do numpy

**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
```
def celcius(n):
    return round((n-32)*5/9, 2);
    
# Dica: T(°C) = (T(°F) - 32) × 5/9
def get_ceusius(F):
    """retorne um array contendo as temperaturas em graus Ceusius
    """
    # YOUR CODE HERE
    
    return list(map(celcius, F));

    raise NotImplementedError()

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-efb7e088b4b1> in <module>
      1 # Validação para nota
----> 2 tf = np.array([0, 12, 45.21, 34, 99.91])
      3 tc = np.array([-17.78, -11.11, 7.34, 1.11, 37.73])
      4 assert (get_ceusius(tf) == tc).all()

NameError: name 'np' is not defined

**Comment by alexlopespereira** [comment]
voce nao importou o numpy
use essa instrucao
import numpy as np

**Comment by lmgbsb** [comment]
Obrigado
