### ISSUE TITLE
Não consegui entrar na sala 

### ISSUE THREAD

**Issue by 1990LFLF** [alexlopespereira/curso_ciencia_dados2020#30]
- não consegui entrar na sala 6 ontem. 
- depois um colega comentou que quem estava na 6 era para ir para a 3. Tentei algumas vezes entrar na 3 e tbm não fui autorizado a entrar, dava um 'timeout'.

Perguntas: 
1 - Para qual sala devo ir?
2 - Devo pedir para alguém me autorizar ou deveria ser automático?

**Comment by rodrigobotelho** [comment]
Converse comigo pelo slack pra gente definir uma sala
