### ISSUE TITLE
2.2 Escreva uma função para obter os itens que não são comuns em duas séries.

### ISSUE THREAD

**Issue by lmgbsb** [alexlopespereira/curso_ciencia_dados2020#32]
**Objetivo que desejo atingir**
estão na uniao mas não na intersecção.

**A solução que já criei até o momento**
```
s1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8]) 
s2 = pd.Series([2, 4, 6, 8, 10, 12]) 
c = pd.Series([1, 3, 5, 7, 10, 12]) 
n=np.union1d(s1, s2)

print(n)

intersecao = s2.isin(s1);
print(intersecao);

n[~intersecao]
```

**Log de erro**
```
[ 1  2  3  4  5  6  7  8 10 12]
0     True
1     True
2     True
3     True
4    False
5    False
dtype: bool

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-11-83ce08e79617> in <module>
     10 print(intersecao);
     11 
---> 12 n[~intersecao]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 6


```

**Comment by claytonsilva007** [comment]
Boa tarde. Para obter a interseção de duas Series você precisa checar a sintaxe da linguagem. Verificar a documentação do método desejado em https://numpy.org/devdocs/reference/generated/numpy.intersect1d.html. Esse é um método direto e de mais fácil compreensão.

Outro ponto que deve ser verificado é que você está fazendo uma negação de elementos que não são booleanos, conforme consta na exceção lançada: "IndexError: boolean index did not match indexed array along dimension 0 ..."

**Comment by lmgbsb** [comment]
Não entendi a explicação. Pode me chamar no slack ou no meet?
