### ISSUE TITLE
Exercício 2.4

### ISSUE THREAD

**Issue by edwsfs** [alexlopespereira/curso_ciencia_dados2020#33]
**Objetivo que desejo atingir**
Alterar o valor do dataframe "df" no campo name de "James" para "Suresh"

**A solução que já criei até o momento**
Consegui gerar um df como indicado na solução, mas ele não valida a resposta.

def change_value(df, col, orig, new):
    result =  df.replace(orig, new, inplace=True)
    return result

RESULTADO DO TESTE
        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d     Suresh    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

**Log de erro**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-1f0d8fe545d1> in <module>
     12 df2 = pd.DataFrame(exam_data2, index=labels)
     13 
---> 14 assert change_value(df, 'name', 'James', 'Suresh').equals(df2)

AttributeError: 'NoneType' object has no attribute 'equals'

**Comment by alexlopespereira** [comment]
já resolveu?

**Comment by edwsfs** [comment]
Ainda não professor, reiniciei o kernel e não funcionou ainda

**Comment by rodrigobotelho** [comment]
Qual a  sala q voce está  pra eu te ajudar?
