### ISSUE TITLE
Erro no exercício 2 -  AttributeError: 'numpy.ndarray' object has no attribute 'reset_index'

### ISSUE THREAD

**Issue by R-Giacomin** [alexlopespereira/curso_ciencia_dados2020#36]
Montei e testei a síntese e está funcionando, mas ao rodar o validate aparece o erro abaixo que não consigo identificar.

**Log de erro**
```
AttributeError: 'numpy.ndarray' object has no attribute 'reset_index'
```

**Comment by rodrigobotelho** [comment]
Favor usar o template de criar issue. Colocar tb o código feito e qual a sala que se encontra pra gente conversar.

**Comment by R-Giacomin** [comment]
Ok. Já resolvi.
