### ISSUE TITLE
Exercícios 4 e 5

### ISSUE THREAD

**Issue by vuviegas** [alexlopespereira/curso_ciencia_dados2020#38]
Ao inserir df[col].replace no código, a validação apresenta erro. Só consigo passar a validação sem especificação da coluna, o que acredito estar errado para a conclusão do exercício.

**Comment by claytonsilva007** [comment]
Qual o exercício que você está tentando resolver? Qual o número da sua sala?

**Comment by vuviegas** [comment]
Sala 3. Tanto o exercício 4 quanto o 5...
