### ISSUE TITLE
Exercício 4

### ISSUE THREAD

**Issue by epdgit** [alexlopespereira/curso_ciencia_dados2020#40]
**Objetivo que desejo atingir**
Não consigo acessar o índice pelo elemento
**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
 x = df[col].isna()
    print(x)

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by claytonsilva007** [comment]
Para acessar um índice de um DataFrame, você precisa utilizar a seguinte 

**seuDataFrame['seuIndexAqui']**

Também é importante relembrar a sintaxe do loc e iloc constantes no slide entitulado de **Filtro e Seleção - Exemplos**.

Casos as dúvidas não tenham sido sanadas, entrarei na sua sala.
