### ISSUE TITLE
Dúvida com exercício 4 e 5

### ISSUE THREAD

**Issue by vcanna** [alexlopespereira/curso_ciencia_dados2020#44]
**Objetivo que desejo atingir**
Ao inserir df[col].replace no código, a validação apresenta erro. Só consigo passar a validação sem especificação da coluna, o que acredito estar errado para a conclusão do exercício.

**A solução que já criei até o momento**
```
  a = df[col].replace('orig', 'new')
    
    return(a)

```

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by claytonsilva007** [comment]
só está faltando fazer a alteração inplace.

https://pt.stackoverflow.com/questions/428164/como-alterar-o-nome-da-coluna-do-dataframe-do-pandas 
Acredito que esse link possa te ajudar, já que não posso te dar a solução diretamente.

**Comment by vcanna** [comment]
Ok, alterei a sintaxe. Funcionou
