### ISSUE TITLE
exercicio 3

### ISSUE THREAD

**Issue by tiagolandi** [alexlopespereira/curso_ciencia_dados2020#45]
**Objetivo que desejo atingir**
Escreva uma função para selecionar as linhas de um dataframe onde o valor na coluna especificada seja ausente (NA)

**A solução que já criei até o momento**
df[df[col].isnull()]

**Log de erro**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-9309357686a2> in <module>
      6 labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
      7 df = pd.DataFrame(exam_data , index=labels)
----> 8 assert seleciona_null(df, 'score').equals(df.loc[['d', 'h']])
      9 seleciona_null(df, 'score')

AttributeError: 'NoneType' object has no attribute 'equals'

**Comment by rodrigobotelho** [comment]
tiago, vc tá retornadno essa solução q vc colou aqui? Quer conversar numa sala? Informe por favor a sala

**Comment by tiagolandi** [comment]
ja resolvi

**Comment by tiagolandi** [comment]
faltou o return na funcao só
