### ISSUE TITLE
2.3 Escreva uma função para selecionar as linhas de um dataframe onde o valor na coluna especificada seja ausente (NA)

### ISSUE THREAD

**Issue by lmgbsb** [alexlopespereira/curso_ciencia_dados2020#46]
**Objetivo que desejo atingir**
2.3 Escreva uma função para selecionar as linhas de um dataframe onde o valor
na coluna especificada seja ausente (NA) 

**A solução que já criei até o momento**
```
#return df[df[col].str.len() == 0]
    return df[df[col] == NaN]
```

**Log de erro**
```

NameError: name 'NaN' is not defined
```

**Comment by lmgbsb** [comment]
Já tentei essas duas soluções mas nenhuma delas funcionou

**Comment by claytonsilva007** [comment]
Você precisa utilizar a função **coluna.isNull()** do dataframe. 

Acredito que esse link possa te ajudar: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isnull.html
