### ISSUE TITLE
2.5 Escreva uma função para mudar o conteúdo de uma coluna de um dataframe de valores do tipo string ('yes' ou 'no') para uma coluna do tipo booleano parametrizando no nome da coluna a ser alterada.

### ISSUE THREAD

**Issue by lmgbsb** [alexlopespereira/curso_ciencia_dados2020#49]
**Objetivo que desejo atingir**
2.5 Escreva uma função para mudar o conteúdo de uma coluna de um dataframe
de valores do tipo string ('yes' ou 'no') para uma coluna do tipo booleano
parametrizando no nome da coluna a ser alterada.

**A solução que já criei até o momento**
```
import numpy as np
import pandas as pd

def change_yes_no(df, col):
    """altere o data frame na coluna col substituindo 'yes' por True e 'no' por False
    """
    s = pd.Series(df[col]);
    s.replace('yes', True, inplace=True)
    s.replace('no', False, inplace=True)
    return df

```

**Log de erro**
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-5-6fa80c4d6956> in <module>
     24 df2 = pd.DataFrame(exam_data2, index=labels)
     25 
---> 26 assert change_yes_no(df, 'qualify').equals(df2)
     27 

AssertionError: 


```

**Comment by lmgbsb** [comment]
Estou na sala 7, se quiser conversar

quando imprimo os dataframes, está funcionando, mas não está passando no assert:


df
        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

df2
        name  score  qualify
a  Anastasia   12.5     True
b       Dima    9.0    False
c  Katherine   16.5     True
d      James    NaN    False
e      Emily    9.0    False
f    Michael   20.0     True
g    Matthew   14.5     True
h      Laura    NaN    False
i      Kevin    8.0    False
j      Jonas   19.0     True

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-10-5dfeb07667f0> in <module>
     29 print("\ndf2")
     30 print(df2)
---> 31 assert change_yes_no(df, 'qualify').equals(df2)
     32 

AssertionError:

**Comment by claytonsilva007** [comment]
Para responder esta questão será necessário dar uma olhadinha da função **map**. Nesta função, você fará o mapeamento dos valores yes para True e  no para False.

**Comment by lmgbsb** [comment]
A função replace já não faz isso?

**Comment by claytonsilva007** [comment]
Dê uma olhadinha nesse link, por favor: https://pandas.pydata.org/pandas-docs/version/0.23.3/generated/pandas.Series.map.html

**Comment by lmgbsb** [comment]
Estou na sala 7

Mesmo erro

## Faça seus testes aqui

import numpy as np

import pandas as pd

​

def change_yes_no(df, col):

    """altere o data frame na coluna col substituindo 'yes' por True e 'no' por False

    """

    s = pd.Series(df[col]);

    #s.replace('yes', True, inplace=True)

    #s.replace('no', False, inplace=True)

    s.map({'yes': True, 'no': False})

    return df

    

    

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',

                       'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],

        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],

        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

exam_data2 = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',

                       'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],

        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],

        'qualify': [True, False, True, False, False, True, True, False, False, True]}

df = pd.DataFrame(exam_data, index=labels) 

df2 = pd.DataFrame(exam_data2, index=labels) 

​

print("\ndf")

print(df)

​

print("\ndf2")

print(df2)

assert change_yes_no(df, 'qualify').equals(df2) 

​

​


df
        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

df2
        name  score  qualify
a  Anastasia   12.5     True
b       Dima    9.0    False
c  Katherine   16.5     True
d      James    NaN    False
e      Emily    9.0    False
f    Michael   20.0     True
g    Matthew   14.5     True
h      Laura    NaN    False
i      Kevin    8.0    False
j      Jonas   19.0     True

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-12-52556bf3db56> in <module>
     30 print("\ndf2")
     31 print(df2)
---> 32 assert change_yes_no(df, 'qualify').equals(df2)
     33 

AssertionError:

**Comment by claytonsilva007** [comment]
s = pd.Series(df[col]);

1. Observe que na linha acima você está fazendo uma cópia de df[col] e atribuindo a variável s  -> s = pd.Series(df[col]); .
2. Você está retornando um dataframe que não foi alterado -> return df
3. A sintaxe da função MAP está correta.

**Comment by lmgbsb** [comment]
tem como fazer essa alteração inline?
