### ISSUE TITLE
Dúvida sobre requisição HTTP - estou na sala 9

### ISSUE THREAD

**Issue by Silmesant** [alexlopespereira/curso_ciencia_dados2020#52]
**Objetivo que desejo atingir**
Suponha que tenho a seguinte API 
url = "https://www.servicos.gov.br/api/v1/servicos/9029" 
Gostaria de entender melhor qual é a diferença entre: 
1) df = requests.get(url).json  e
2) df_= pd.read_json(url)
No primeiro preciso importar a bilbioteca request; no segundo não. Minha dúvida é: ambos não são um HTTP request? Quando decidir qual método usar?
**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
```

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by rodrigobotelho** [comment]
O segundo caso o próprio pandas faz o request e carrega o json. Pra saber o que o pandas usa para fazer esse request teria q verificar no código do pandas. Se ele usar o request, o pandas vai ter o import do request, não precisando de importar novamente para usar o pandas.
A decisão de qual usar é  muito pessoal. Se você quer manipular o json antes, talvez usar o request pode ser mais fácil. Apesar que pelo pandas tb dá  pra  manipular o resultado.
