### ISSUE TITLE
Problema no exercício 1

### ISSUE THREAD

**Issue by vuviegas** [alexlopespereira/curso_ciencia_dados2020#54]
Consigo retornar o valor respectivo da busca pelo estado (média do IDEB), mas a validação não passa:

AssertionError                            Traceback (most recent call last)
<ipython-input-138-b61a139ea9a8> in <module>
      5 # Use os argumentos skiprows e skipfooter para carregar a tabela corretamente.
      6 ###################################
----> 7 assert media_ideb(df_ideb, 'DF') == 3.4
      8 assert round(media_ideb(df_ideb, 'SP'),2) == 4.04
      9 assert round(media_ideb(df_ideb, 'GO'),2) == 4.24

AssertionError:

**Comment by claytonsilva007** [comment]
Dúvida sanada em sala virtual.
