### ISSUE TITLE
Problema com o exercício 1 - Não sabemos por onde começar na sala

### ISSUE THREAD

**Issue by vcanna** [alexlopespereira/curso_ciencia_dados2020#55]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.
Estamos tendo dificuldade de iniciar o exercício na sala 4
**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
```

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by claytonsilva007** [comment]
Irei entrar em sua sala.
