### ISSUE TITLE
df.replace - exercício 3.1

### ISSUE THREAD

**Issue by lmgbsb** [alexlopespereira/curso_ciencia_dados2020#56]
**Objetivo que desejo atingir**
substitua valores '-' por np.nan (NA) com o metodo replace.

**A solução que já criei até o momento**
```
df_ideb = pd.read_excel('../../curso_ciencia_dados2020/data/originais/ideb/ideb_municipios2017.xlsx')
#df_ideb
df_ideb.replace(to_replace="-", value=np.nan) 
df_ideb
```

**Log de erro**
```
Não está dando erro mas também não está substituindo
```

**Comment by claytonsilva007** [comment]
Boa tarde. 

Você precisa checar a sintaxe do método replace. Para isso, recomendo que acesse o link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html

Segue um exemplo retirado da página do manual do pandas: df.replace({0: 10, 1: 100})

**Comment by lmgbsb** [comment]
Não estou conseguindo evoluir. Preciso de ajuda na sala 7. Obrigado

**Comment by rodrigobotelho** [comment]
Atendi ele pelo meeting
