### ISSUE TITLE
Exercício 4

### ISSUE THREAD

**Issue by marinarcaetano** [alexlopespereira/curso_ciencia_dados2020#6]
**Objetivo que desejo atingir**
Escreva uma função Python para gerar um dicionário que contenha um número (entre 1 e n) no formato (x, x * x).

**A solução que já criei até o momento**
```
def create_dict(n):
    """retorne um dicionário com pares (x, x*x)
    """
    # YOUR CODE HERE
    m = {x: x*x for x in range (1,n+1)}
    print(m)
```

**Log de erro**
```
AssertionError                            Traceback (most recent call last)
<ipython-input-296-eca3ea218a81> in <module>
      1 # Validação para nota
----> 2 assert create_dict(5) == {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

AssertionError: 

```

**Comment by halisson-gomides** [comment]
Tentando contribuir, sugiro que substitua o comando `print(m)` por `return m`

**Comment by marinarcaetano** [comment]
Beleza! Funcionou. Obrigada!

**Comment by stefanomozart** [comment]
Fechando a issue já que o problema foi resolvido.
