### ISSUE TITLE
Como salvar o df em sqlite

### ISSUE THREAD

**Issue by tiagolandi** [alexlopespereira/curso_ciencia_dados2020#60]
**Objetivo que desejo atingir**
salvar dataframe como sqlite

**A solução que já criei até o momento**
def save_to_sqlite(df, table_name, con_str):
    df.index.names = ['index']
    con = sqla.create_engine(con_str)
    df_sql = df.to_sql(table_name, con, if_exists="replace")
    return df_sql

**Log de erro**
InvalidRequestError: Could not reflect: requested table(s) not available in Engine(sqlite:///../..//curso_ciencia_dados2020/data/processados/idhm/idhm2013.sqlite): (IDHM)

**Comment by tiagolandi** [comment]
SALA 9

**Comment by claytonsilva007** [comment]
A sintaxe que você especificou está correta. Tente converter o nome da tabela para minúsculo usando a função lower().

Ver link: [https://github.com/SAP/sqlalchemy-hana/issues/22#issuecomment-383077976](url)

**Comment by tiagolandi** [comment]
ok resolvido
