### ISSUE TITLE
preciso de ajuda no exercicio 3.3

### ISSUE THREAD

**Issue by adilsonsc** [alexlopespereira/curso_ciencia_dados2020#66]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.

**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
```

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by claytonsilva007** [comment]
estou tentando entrar em sua sala, mas não consegui.
