### ISSUE TITLE
Problema no score do feedback

### ISSUE THREAD

**Issue by tiagolandi** [alexlopespereira/curso_ciencia_dados2020#68]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.

**A solução que já criei até o momento**
teste é validado mas o score é 0.0/1.0
exercicio 3.2

**Log de erro**
InvalidRequestError: Could not reflect: requested table(s) not available in Engine(sqlite:///../..//curso_ciencia_dados2020/data/processados/idhm/idhm2013.sqlite): (idhm)

**Comment by fabiobruni** [comment]
Para mim acontece a mesma coisa com o exercício 3.1

**Comment by rodrigobotelho** [comment]
Execute em uma célula o seguinte comando:

**Comment by tiagolandi** [comment]
../../curso_ciencia_dados2020/data/processados/idhm/idhm2013.sqlite

**Comment by vuviegas** [comment]
O meu erro é o seguinte:

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(sqlite:///../..//curso_ciencia_dados2020/data/processados/idhm/idhm2013.sqlite): (idhm)

**Comment by vuviegas** [comment]
O meu erro é o seguinte:

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(sqlite:///../..//curso_ciencia_dados2020/data/processados/idhm/idhm2013.sqlite): (idhm)

Ou seja, apesar de a minha validação passar com sucesso, eu submeto o exercício e o feedback retornado é de que meu Score é 0 (zero)...

**Comment by rodrigobotelho** [comment]
Não está conseguindo salvar o seu sql. Rode apenas sua função e tente fazer o:
!ls ../..//curso_ciencia_dados2020/data/processados/idhm/idhm2013.sqlite
em uma outra célula. Se o arquivo não existir é pq existe um problema na sua função.

**Comment by rodrigobotelho** [comment]
Outros alunos tem reclamado desse problema q só ocorre no feedback. Já repassei o problema para o professor.
