### ISSUE TITLE
Sala 7 - Preciso de ajuda no exercício 3.4

### ISSUE THREAD

**Issue by lmgbsb** [alexlopespereira/curso_ciencia_dados2020#69]
**Objetivo que desejo atingir**
Escreva uma função para fazer o merge dos dataframes de população e de PIB de 2017. A função deve receber como parâmetro o caminho para cada um dos dataframes

**A solução que já criei até o momento**
```
Não sei por onde começar
```

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by rodrigobotelho** [comment]
Você deve criar dois dataframes, o de População e outro do pib dos municípios. Você deve observar as dicas que professor deu:

**Comment by rodrigobotelho** [comment]
# Dica 1: A coluna que contem o código IBGE do município deve ter o mesmo formato (string) e a mesma
#         quantidade de caracteres nas duas tabelas.
# Dica 2: Converta o codigo do município para string ao carregar o dataframe de população utilizando
#         o mapeamento de tipos dtype={'cod_munic': str, 'cod_uf': str}. Assim o codigo do municipio não perde
#         os zeros a esquerda.
# Dica 3: Concatene o codigo da UF com o código do município usando o operador + e salve em outra coluna.
# Dica 4: Use o código apresentado na aula para carregar o dataframe do PIB de 2017, especifique o dtype da
#         coluna que contém o codigo do municipio.
# Dica 5: Renomeie as colunas apropriadamente.
# Dica 6: Depois que os dois dataframes tiverem o codigo ibge (com valores equivalentes
#         e mesmo tipo de dados) você pode fazer o merge.

Observe que ele ensina como faz pra criar o codigo ibge nos dois dataframes e aí vc consegue fazer o merge usando essa colula.
