### ISSUE TITLE
Exercício 9

### ISSUE THREAD

**Issue by luisssguilherme** [alexlopespereira/curso_ciencia_dados2020#7]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar:
Escreva uma função Python para criar um array numpy 2D com 1s nos elementos das bordas e com 0s no interior. O tamanho do array deve ser parametrizável.

```
Cole aqui o código que você já criou para atingir seu objetivo:
import numpy as np
# Dica: A função ones do pacote numpy cria um array de 1s
def create_array(n):
    """retorne um array 2d preenchido com 1s nas bordas e 0s no interior 
    """
    x = np.ones((n,n))
    print(x)
    x[1:-1,1:-1] = 0
    print(x)
    return result
    create_array(n)
```

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código:
"name 'x' is not defined"
```

**Comment by halisson-gomides** [comment]
Tentando contribuir, acredito que a variável que precisa ser definida é `result`. Sugiro substituir por `x`
Para fazer a chamada da função ela precisa estar devidamente identada também, como a seguir:
`def create_array(n):
    x = np.ones((n,n))
    print(x)
    x[1:-1,1:-1] = 0
    print(x)
    return x

create_array(5)`

**Comment by luisssguilherme** [comment]
Funcionou! Muito obrigado, @halisson-gomides !
