### ISSUE TITLE
Problemas no Score do Feedback - Aula 3, Exercício 2

### ISSUE THREAD

**Issue by vuviegas** [alexlopespereira/curso_ciencia_dados2020#70]
Apesar de a minha validação passar com sucesso, eu submeto o exercício e o feedback retornado é de que meu Score é 0 (zero)...

O meu erro é o seguinte, no arquivo de feedback:

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(sqlite:///../..//curso_ciencia_dados2020/data/processados/idhm/idhm2013.sqlite): (idhm)

Já tentei refatorar o código, copiar o código de colegas que conseguiram passar o teste, e nada retorna resultado satisfatório.

**Comment by vuviegas** [comment]
path_idhm='../../curso_ciencia_dados2020/data/originais/idhm/idhm2013.xlsx'
df_idhm = pd.read_excel(path_idhm, sheet_name="IDHM")
table_name = 'IDHM'
con_str='sqlite:///../../curso_ciencia_dados2020/data/processados/idhm/idhm2013.sqlite'

def save_to_sqlite(df, table_name, con_str):
    con = sqla.create_engine(con_str)
    df.index.names = ['index']
    return df.to_sql('idhm', con, if_exists="replace")

**Comment by vuviegas** [comment]
O erro que aparece no meu feedback é aquele ali:
InvalidRequestError: Could not reflect: requested table(s) not available in Engine(sqlite:///../..//curso_ciencia_dados2020/data/processados/idhm/idhm2013.sqlite): (idhm)

Mas a minha validação passa sem erros ou problemas.

**Comment by claytonsilva007** [comment]
Tenho algumas sugestões para que você cheque se está tudo OK:

1. o dataframe **df_idhm** está sendo carregado? caso positivo, passamos pela primeira etapa de resolução do problema.
`path_idhm='../../curso_ciencia_dados2020/data/originais/idhm/idhm2013.xlsx'
df_idhm = pd.read_excel(path_idhm, sheet_name="IDHM")
table_name = 'IDHM'
con_str='sqlite:///../../curso_ciencia_dados2020/data/processados/idhm/idhm2013.sqlite'`

2. Passe para a função `def save_to_sqlite(df, table_name, con_str):` as variáveis que você definiu em seus testes: df_idhm , df_idhm, table_name e con_str.

3. experimente remove essa linha: `df.index.names = ['index']`.

4. Por fim, execute os seguintes passos:
a) utilize o método **sqla.create_engine** para se conectar ao banco de dados
b) utilize o método **to_sql** para para salvar seu dataframe no banco de dados.

Esse erro ocorre quando a tabela não foi encontrada em seu banco de dados. Favor dar uma olhadinha nesse link: [https://github.com/SAP/sqlalchemy-hana/issues/22#issuecomment-383077976](url).

**Comment by vuviegas** [comment]
Não tá muito claro pra mim... Eu tô com muita dificuldade nesse modo do curso. eu vou tentar aqui com esse roteiro que você postou.

**Comment by vuviegas** [comment]
Oi. Segui os passos que foram informados. Exclui o df.index.names do meu método, chamei nele o sqla.create_engine e o to_sql, como já estava. A validação, mais uma vez, está passando sem erros... No entanto, meu feedback mostra o mesmo erro... O link que você enviou não está abrindo... Não consigo ler sobre a resolução.

Será que eu deleto o arquivo, faço novamente o fetch do assignment e refaço o exercício? Meu medo é que ele quebre algum erro, vi colegas fazendo isso e o Jupiter retornar erros...

**Comment by vuviegas** [comment]
Oi, consegui resolver de outra forma. Precisei excluir o database da pasta code_bootcamp e rodar novamente o código refatorado. De qualquer forma, obrigado pela ajuda!
