### ISSUE TITLE
Problema: score - feedback - aula3 -  exercícios 6 e 7

### ISSUE THREAD

**Issue by rcostafl** [alexlopespereira/curso_ciencia_dados2020#71]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.

**A solução que já criei até o momento**
``` A solução foi implementada e validada nos exercícios. Entretannto, o feedback retorna zerado!

Cole aqui o código que você já criou para atingir seu objetivo.
```

**Log de erro**
```

Cole aqui o log de erro gerado pela execução do seu código.
AssertionErrorTraceback (most recent call last)
<ipython-input-5-4e9f99aa2abf> in <module>
     16 cidades_0_9_y['pib_percapita'] = cidades_0_9_y['pib_percapita'].apply(lambda x: round(x, 1))
     17 
---> 18 assert cidades_0_9.to_dict() == test_data or cidades_0_9_y.to_dict() == test_data

AssertionError:

**Comment by rodrigobotelho** [comment]
Isso ocorre quando o resultado tá diferente do assert.
Imprima oq  essas variáveis:
cidades_0_9 = top10(pib_percapita_2017, 'pib_percapita')[['cod_ibge7', 'municipio', 'uf', 'pib_percapita']].iloc[[0,9]]
cidades_0_9_y = top10(pib_percapita_2017, 'pib_percapita')[['cod_ibge7', 'municipio_y', 'uf', 'pib_percapita']].iloc[[0,9]]
e compare com:
test_data = {'cod_ibge7': {3677: '3536505', 3547: '3524709'},
             'municipio': {3677: 'Paulínia', 3547: 'Jaguariúna'},
             'uf': {3677: 'SP', 3547: 'SP'},
             'pib_percapita': {3677: 344.8, 3547: 209.3}}
Veja o q tá diferente. Isso vai ser determinante pra saber qual é o erro.
Por favor, lembre-se de colocar na issue o seu código e qual sala q se encontra

**Comment by rcostafl** [comment]
Rodrigo, eu já havia feito isso, mas não consegui identificar o problema sozinho, por isso abri a issue.

Eu colei, em minha área de testes o conteúdo da célula de validação. A única mudança foi que tirei a plavra "assert" do seguinte comando: assert cidades_0_9.to_dict() == test_data or cidades_0_9_y.to_dict() == test_data

Assim, o final da execução fo comando de teste é o seguinte: cidades_0_9.to_dict() == test_data or cidades_0_9_y.to_dict() == test_data .

A saída do comando acima é True.

Seguem os dados impressos para análise.

test_data = {'cod_ibge7': {3677: '3536505', 3547: '3524709'},
             'municipio': {3677: 'Paulínia', 3547: 'Jaguariúna'},
             'uf': {3677: 'SP', 3547: 'SP'},
             'pib_percapita': {3677: 344.8, 3547: 209.3}}

# Na minha opinião, está igual o test_data (não encontrei a diferença)
cidades_0_9.to_dict()  

{'cod_ibge7': {3677: '3536505', 3547: '3524709'},
 'municipio': {3677: 'Paulínia', 3547: 'Jaguariúna'},
 'uf': {3677: 'SP', 3547: 'SP'},
 'pib_percapita': {3677: 344.8, 3547: 209.3}}

# Nos dados abaixo, o nomes do município contém a sigla do estado, mas, pelo teste, basta que os dados de cidades_0_9 estejam corretos para que o teste seja considerado válido.

cidades_0_9_y.to_dict()
{'cod_ibge7': {3677: '3536505', 3547: '3524709'},
 'municipio_y': {3677: 'Paulínia (SP)', 3547: 'Jaguariúna (SP)'},
 'uf': {3677: 'SP', 3547: 'SP'},
 'pib_percapita': {3677: 344.8, 3547: 209.3}}

Sugiro que faça uma chamada no slack após a aula.

**Comment by rodrigobotelho** [comment]
Avisei o professor do problema que está ocorrendo no feedback
