### ISSUE TITLE
Exercício 4.2 - HELP - Por favor, preciso de ajuda no exercício 4.2 - estou travado aqui

### ISSUE THREAD

**Issue by hugoee** [alexlopespereira/curso_ciencia_dados2020#72]
Por favor, preciso de ajuda no exercício 4.2 , para desmembrar uma coluna em duas outras colunas.

**Comment by rodrigobotelho** [comment]
Dá  uma olhada na função apply do pd.Series (você vai ter que rodar numa coluna, por isso q é uma função do Series). A função apply recebe uma função que será  aplicada em cada item da coluna. Essa função receberá  como argumento um item da coluna e você poderá assim fazer o desmembramento. Observe também q a coluna em questão é uma string. Procure na primeira aula as funções de  string, principalmente, a função split. Pra finalizar a dica, procure por funções lambda, vai deixar a resolução ainda mais facilitado.
