### ISSUE TITLE
Ajuda no exercício 4.2 - erro no parse

### ISSUE THREAD

**Issue by Silmesant** [alexlopespereira/curso_ciencia_dados2020#74]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.
Estou simplesmente tentando ler um csv com a função read_csv, mas está dando o seguinte erro:
ParserError: Error tokenizing data. C error: Expected 2 fields in line 4, saw 4
**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
```
path_gini = '../../curso_ciencia_dados2020/data/originais/gini/ginibr.csv'
df_gini = pd.read_csv(path_gini)

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by rodrigobotelho** [comment]
Observe que o separador desse csv é diferente dos outros. Você pode ir pelo files e baixar o arquivo ou executar o seguinte comando:
 !head ~/work/curso_ciencia_dados2020/data/originais/gini/ginibr.csv

**Comment by rodrigobotelho** [comment]
Estou fechaando a issue por inatividade. Se ainda tiver alguma dúvida pode vir falar comigo
