### ISSUE TITLE
Preciso de ajuda no exercicio 4.3 - nao estou entendendo bem o que esta sendo pedido

### ISSUE THREAD

**Issue by adilsonsc** [alexlopespereira/curso_ciencia_dados2020#75]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.

**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
```

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by rodrigobotelho** [comment]
Observe a documetação da função:
"Retorna um dataframe com os nomes das colunas, o total e a porcentagem de valores
       NA no dataframe"
Além disso olhe a dica:
# Dica: Use a função concat para concatenar duas séries. Especifique axis=1 para concatenar
#       por colunas. Se quiser dar nome as colunas depois de concatenar, utilize o argumento
#       keys=['Total','Porcentage']
Assim, o professor deseja que você crie duas Series com o total de NA e outra com a Porcentagem de NA. Depois concatene essas duas series  como ele  falou na dica.

**Comment by rodrigobotelho** [comment]
Observe tb um detalhe importante é observar o assert que o professor fez pra tentar deixar os dados como ele quer, como o arredondamento de float e etc.
