### ISSUE TITLE
nao consigo finalizar o ex 3.4

### ISSUE THREAD

**Issue by louloucostaesilva** [alexlopespereira/curso_ciencia_dados2020#81]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.

**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
```

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by claytonsilva007** [comment]
Você poderia postar aqui os problemas que está enfrentando? Até que ponto você conseguiu evoluir?

**Comment by louloucostaesilva** [comment]
Consegui resolver. Obrigada

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
