### ISSUE TITLE
Preciso de ajuda com o exercicio 1

### ISSUE THREAD

**Issue by adilsonsc** [alexlopespereira/curso_ciencia_dados2020#83]
Ja tentei de diversas formas mas nao consigo plotar o grafico

**Comment by rodrigobotelho** [comment]
Por favor coloque o código e o erro, alem da sala em q se encontra.

**Comment by adilsonsc** [comment]
cara, nao tem codigo de erro. estou fazendo varias tentativas mas nao consigo plotar. talvez eu nao tenha entendido bem os conceitos

**Comment by adilsonsc** [comment]
ja consultei os slides da aula, mas nao ta me ajudando. Estou tentando ahcar na web tbm mas ate agora nao consegui nada que ajude

**Comment by claytonsilva007** [comment]
Problema resolvido em sala.
