### ISSUE TITLE
Por favor, preciso de ajuda com o exercício 5.1 (sala 5 ou slack, por favor)

### ISSUE THREAD

**Issue by hugoee** [alexlopespereira/curso_ciencia_dados2020#84]
Por favor, preciso de ajuda com o exercício 5.1 (sala 5 ou slack, por favor)

ValueError: Image size of 836x86736 pixels is too large. It must be less than 2^16 in each direction.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/opt/conda/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

/opt/conda/lib/python3.8/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/opt/conda/lib/python3.8/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

/opt/conda/lib/python3.8/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2208 
   2209             try:
-> 2210                 result = print_method(
   2211                     filename,
   2212                     dpi=dpi,

/opt/conda/lib/python3.8/site-packages/matplotlib/backend_bases.py in wrapper(*args, **kwargs)
   1637             kwargs.pop(arg)
   1638 
-> 1639         return func(*args, **kwargs)
   1640 
   1641     return wrapper

/opt/conda/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args)
    507             *metadata*, including the default 'Software' key.
    508         """
--> 509         FigureCanvasAgg.draw(self)
    510         mpl.image.imsave(
    511             filename_or_obj, self.buffer_rgba(), format="png", origin="upper",

/opt/conda/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    400     def draw(self):
    401         # docstring inherited
--> 402         self.renderer = self.get_renderer(cleared=True)
    403         # Acquire a lock on the shared font cache.
    404         with RendererAgg.lock, \

/opt/conda/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py in get_renderer(self, cleared)
    416                           and getattr(self, "_lastKey", None) == key)
    417         if not reuse_renderer:
--> 418             self.renderer = RendererAgg(w, h, self.figure.dpi)
    419             self._lastKey = key
    420         elif cleared:

/opt/conda/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py in __init__(self, width, height, dpi)
     94         self.width = width
     95         self.height = height
---> 96         self._renderer = _RendererAgg(int(width), int(height), dpi)
     97         self._filter_renderers = []
     98 

ValueError: Image size of 836x86736 pixels is too large. It must be less than 2^16 in each direction.

<Figure size 841.6x288 with 1 Axes>

**Comment by claytonsilva007** [comment]
Boa tarde. 

Gostaria que você postasse aqui o trecho de código já desenvolvido.

**Comment by hugoee** [comment]
path_gini='../../curso_ciencia_dados2020/data/originais/gini/ginibr.csv'

df = pd.read_csv(path_gini, engine='python', sep=";", na_values='...', decimal=",", skiprows=2, skipfooter=1)

df

df_unpivoted = df.melt(id_vars=['Município'], var_name='data', value_name='gini')

df_unpivoted.head(50)

g = sns.catplot(x="data", y="gini", hue="Município", height=4, aspect=2, kind="box", data=df_unpivoted);

**Comment by hugoee** [comment]
Rodrigo, conseguimos achar o problema. A questão era este argumento ->  hue="Município" .

Tirarmos o "hue"  e deu certo !

Obrigado, Rodrigo !!!

**Comment by hugoee** [comment]
Clayton, conseguimos achar o problema. A questão era este argumento ->  hue=“Município” .

Tirarmos o “hue”  e deu certo !

Obrigado, Clayton !!!
