### ISSUE TITLE
ajuda para desenvolver o ex 5.1 sala 2 

### ISSUE THREAD

**Issue by louloucostaesilva** [alexlopespereira/curso_ciencia_dados2020#86]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.

**A solução que já criei até o momento**
```
 YOUR CODE HERE
df_indi_gini = pd.read_csv(path_gini, na_values=',')
df_indi_gini

```

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by claytonsilva007** [comment]
Você poderia postar o erro?

**Comment by rodrigobotelho** [comment]
observe q o csv do gini o separador é ;. Coloque sep='; '.
