### ISSUE TITLE
Problema no score dos exercícios da Aula 2

### ISSUE THREAD

**Issue by vuviegas** [alexlopespereira/curso_ciencia_dados2020#87]
Fiz todos os exercícios obrigatórios até o momento (exceto o Aula 06, Exercício 03). Ocorre que as notas dos exercícios obrigatórios da Aula 02, quais sejam, 01, 02 e 03, não estaão contabilizando a minha nota, mesmo depois de a validação de todos eles estar correta. Não  é problema do meu código, pois o erro do Score é o seguinte:

NameError: name 'pd' is not defined

Ciente que os Scores estavam zerados, eu deletei os arquivos de feedback e sumeti novamente todos os exercícios. Ocorre que não consigo fazer fetch feedback dos exercícios. Minha nota está comprometida por erro do sistema, e preciso de ajuda para resolver isso... Grato pela atenção!

**Comment by claytonsilva007** [comment]
`NameError: name 'pd' is not defined`

Gostaria que você checasse se o pandas está devidamente importado em seu jupyter. 
Caso o problema persista, o professor Alex e a equipe ENAP irá irá dar uma solução para isso.

**Comment by vuviegas** [comment]
Aula 2 - Ex 01

![image](https://user-images.githubusercontent.com/64157358/96629879-95372b00-12ea-11eb-8ea0-fdbe6ef25554.png)

**Comment by vuviegas** [comment]
Aula 02 - Ex 02

![image](https://user-images.githubusercontent.com/64157358/96630025-c44d9c80-12ea-11eb-9007-ad9642f178a2.png)

**Comment by vuviegas** [comment]
Aula 02 - Ex 03

![image](https://user-images.githubusercontent.com/64157358/96630098-e6dfb580-12ea-11eb-86cb-d132531af5d4.png)

**Comment by vuviegas** [comment]
![image](https://user-images.githubusercontent.com/64157358/96630222-1098dc80-12eb-11eb-9750-77476cb2a3c2.png)

**Comment by vuviegas** [comment]
![image](https://user-images.githubusercontent.com/64157358/96630402-581f6880-12eb-11eb-8eb2-032c4cf4e9b8.png)
Submeti os exercícios novamente e exclui todos os feedbacks que estavam zerados, na esperança de que eu pudesse fazer um novo fetch feedback. Mas mesmo após 10 minutos de espera, o Jupyter não retorna a opção "available feedback"...

**Comment by vuviegas** [comment]
Sim, o pandas está importado, conforme PrintScreen que enviei acima... Todos os outros exercícios que necessitam do pandas estão funcionando normalmente!

**Comment by vuviegas** [comment]
Oi Alex, encaminhei os arquivos no seu email:

alexlopespereira@gmail.com
