### ISSUE TITLE
Exercício 5.3

### ISSUE THREAD

**Issue by marcostc** [alexlopespereira/curso_ciencia_dados2020#88]
Estou tendo dificuldade com o filtro de atenuação para aplicação da função de inflexã.

**Comment by gui-gafa** [comment]
Estou tentando entender o que ele quer no exercício, tu encontrou a média dos períodos?

**Comment by rodrigobotelho** [comment]
Você poderia colocar o código que você já implementou?

**Comment by rodrigobotelho** [comment]
Se puder colocar a sala, eu posso ajudar tb.
