### ISSUE TITLE
Continuo com dificuldade pra fazer o exercicio 6.3

### ISSUE THREAD

**Issue by adilsonsc** [alexlopespereira/curso_ciencia_dados2020#89]
**Objetivo que desejo atingir**
Escreva uma descrição clara e concisa do que deseja realizar.

**A solução que já criei até o momento**
```
Cole aqui o código que você já criou para atingir seu objetivo.
```

**Log de erro**
```
Cole aqui o log de erro gerado pela execução do seu código.
```

**Comment by rodrigobotelho** [comment]
Podia ter descrito melhor o problema. Oq você já fez, qual é a sua dificuldade e qual sala em q se encontra.

**Comment by adilsonsc** [comment]
eu ja tentei varias coisas, se tiver que descrever tudo aqui vai me atrapalhar mais que ajudar

**Comment by rodrigobotelho** [comment]
Você poderia pelo menos colocar a sala pra eu poder tentar te ajudar.
